<?php

return [
    'color'                => 'RGB эсвэл Hex өнгө (заавал биш)',
    'color_ph'             => 'Өнгө, жишээ нь. #ffffff эсвэл rgb(255, 255, 255)',
    'create_new_item'      => 'Шинэ цэс үүсгэх',
    'delete_item_confirm'  => 'Тийм, энэ цэсийг устга',
    'delete_item_question' => 'Та энэ цэсийг устгахдаа итгэлтэй байна уу?',
    'drag_drop_info'       => 'Доорх цэсүүдийг зөөж цэгцлэнэ үү',
    'dynamic_route'        => 'Динамик замчлал',
    'edit_item'            => 'Цэсийг засах',
    'icon_class'           => 'Цэсний үсгийн класс (',
    'icon_class2'          => 'Voyager үсгийн класс хэрэглэгч</a>)',
    'icon_class_ph'        => 'Зургийн класс (заавал биш)',
    'item_route'           => 'Цэс - д замчлал хийх',
    'item_title'           => 'Цэсний гарчиг',
    'link_type'            => 'Линкны төрөл',
    'new_menu_item'        => 'Шинэ цэс',
    'open_in'              => 'Нээх',
    'open_new'             => 'Шинэ таб/Цонх',
    'open_same'            => 'Өөр таб/Цонх',
    'route_parameter'      => 'Замчлалын параметр (хэрэв байгаа бол)',
    'static_url'           => 'Статик URL',
    'successfully_created' => 'Шинэ цэс амжилттай үүсгэлээ',
    'successfully_deleted' => 'Цэс амжилттай устгагдлаа',
    'successfully_updated' => 'Цэс амжилттай засагдлаа',
    'updated_order'        => 'Цэсний байрлал амжилттай солигдлоо',
    'url'                  => 'Цэсний URL',
    'usage_hint'           => 'Та цэсийг сайтынхаа аль ч хэсэгт гаргах боломжтой',
];
