<?php

return [
    'usage_help'           => 'Та сайтынхаа аль ч тохируулга бүрийн утгыг дуудаж авах боломжтой',
    'save'                 => 'Тохиргоог хадгалах',
    'new'                  => 'Шинэ тохиргоо',
    'help_name'            => 'Setting name ex: Admin Title Нэр тохируулах, жишээ нь: Админ гарчиг',
    'help_key'             => 'Түлхүүр тохируулах, жишээ нь: admin_title',
    'help_option'          => '(заавал биш, тохирох хэлбэрийн талбарт тохирсон сонголтуудыг ашиглана)',
    'add_new'              => 'Шинэ тохиргоо нэмэх',
    'delete_question'      => ':setting Setting - ийг устгахдаа итгэлтэй байна уу?',
    'delete_confirm'       => 'Тийм, энэ тохиргоог устга',
    'successfully_created' => 'Тохиргоо амжилттай хийгдлээ',
    'successfully_saved'   => 'Тохиргоо амжилттай хадгалагдлаа',
    'successfully_deleted' => 'Тохиргоо амжилттай устгагдлаа',
    'already_at_top'       => 'Энэ нь жагсаалтын эхэнд аль хэдийн орсон байна',
    'already_at_bottom'    => 'Энэ нь жагсаалтын сүүлд аль хэдийн орсон байна',
    'key_already_exists'   => 'key :key аль хэдийн байна',
    'moved_order_up'       => ':name тохиргоо дээшээ шилжлээ',
    'moved_order_down'     => ':name тохиргоо доошоо шилжлээ',
    'successfully_removed' => ':name - ийн утгыг амжилттай устгалаа',
    'group_general'        => 'Ерөнхий',
    'group_admin'          => 'Админ',
    'group_site'           => 'Сайт',
    'group'                => 'Грүпп',
    'help_group'           => 'Энэ тохиргоог бүлэгт хуваарилсан байна',
];
